name: Sitebuilder upload

# Run this workflow whenever commits are pushed to the master branch
on:
  push:
    branches:
      - master

env:
    SB_PATH: /fac/sci/dcs/teaching/material/cs141/test 

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        # Clone the repository
        - uses: actions/checkout@v1

        # Initialise the ./bin directory
        - name: Initialisation 
          run: mkdir bin 

        # Download sitebuilder-util
        - name: Download sitebuilder-util
          uses: Legion2/download-release-action@v2.1.0
          with:
            repository: mbg/sitebuilder-util
            tag: 'latest'
            path: bin
            file: sitebuilder-util

        # Publish the files from this repository to Sitebuilder
        - name: Publish to Sitebuilder 
          env: 
            SB_USER: ${{ secrets.SB_USER }}
            SB_PASSWORD: ${{ secrets.SB_PASSWORD }}
          run: |
            sudo chmod +x ./bin/sitebuilder-util
            ./bin/sitebuilder-util edit --page=$SB_PATH --file=content.html
            for f in ./files/*; do ./bin/sitebuilder-util upload --page=$SB_PATH --file=$f --name=$(basename $f); done